version: 0.1.{build}
skip_tags: true
configuration:
- Debug
- Release
build:
  verbosity: normal
before_package:
- ps: Copy-Item C:\projects\3d-engine\$env:CONFIGURATION\SuStoEngine.exe C:\projects\3d-engine\SuStoEngine\Resources\.
artifacts:
- path: SuStoEngine\Resources
  name: Engine
deploy:
- provider: GitHub
  auth_token:
    secure: 2ot2rVNY4Vcru0qcNVy1a7JafEvIY1XCNN9dEHAwZVIf+XYp4GIjJNyKxJCG74og
  artifact: Engine
  on:
    CONFIGURATION: Release